/// Plain-language explanations for the words the calculator colors as
/// operators. These stay separate from parsing so help text cannot affect
/// how an expression is interpreted.
const Map<String, String> calcKeywordHelp = {
  'to': 'Converts the value to another unit or currency.',
  'into': 'Converts the value to another unit or currency.',
  'of': 'Multiplies by the value or amount that follows.',
  'off': 'Subtracts a percentage from the value that follows.',
  'on': 'Adds a percentage to the value that follows.',
  'as': 'Expresses a value in another form, such as a percentage.',
  'in': 'Converts a value to another unit. It can also mean inches.',
  'per': 'Divides the value on the left by the value on the right.',
  'mod': 'Returns the remainder after division.',
  'and': 'Adds numbers, or requires both true/false values to be true.',
  'or': 'Is true when either value is true.',
  'xor': 'Applies integer XOR, or compares two true/false values.',
  'not': 'Reverses a true or false value.',
  'a': 'Connects natural-language percentage expressions.',
  'an': 'Connects natural-language percentage expressions.',
  'plus': 'Adds the value on the right to the value on the left.',
  'with': 'Adds the value on the right to the value on the left.',
  'minus': 'Subtracts the value on the right from the value on the left.',
  'subtract': 'Subtracts the value on the right from the value on the left.',
  'without': 'Subtracts the value on the right from the value on the left.',
  'times': 'Multiplies the value on the left by the value on the right.',
  'multiply': 'Multiplies the value on the left by the value on the right.',
  'multiplied': 'Multiplies the value on the left by the value on the right.',
  'mul': 'Multiplies the value on the left by the value on the right.',
  'divide': 'Divides the value on the left by the value on the right.',
  'divided': 'Divides the value on the left by the value on the right.',
  'by': 'Completes a written multiplication or division phrase.',
  'over': 'Divides the value on the left by the value on the right.',
  'percent': 'Treats the number as a percentage.',
  'pct': 'Treats the number as a percentage.',
  'binary': 'Writes the result in base 2.',
  'bin': 'Writes the result in base 2.',
  'octal': 'Writes the result in base 8.',
  'oct': 'Writes the result in base 8.',
  'hexadecimal': 'Writes the result in base 16.',
  'hex': 'Writes the result in base 16.',
  'decimal': 'Writes the result in base 10.',
  'dec': 'Writes the result in base 10.',
  'scientific': 'Writes the result in scientific notation.',
  'sci': 'Writes the result in scientific notation.',
  'thousand': 'Scales the number by one thousand.',
  'thousands': 'Scales the number by one thousand.',
  'million': 'Scales the number by one million.',
  'millions': 'Scales the number by one million.',
  'billion': 'Scales the number by one billion.',
  'billions': 'Scales the number by one billion.',
  'trillion': 'Scales the number by one trillion.',
  'trillions': 'Scales the number by one trillion.',
  'lakh': 'Scales the number by one lakh.',
  'lakhs': 'Scales the number by one lakh.',
  'lac': 'Scales the number by one lakh.',
  'lacs': 'Scales the number by one lakh.',
  'crore': 'Scales the number by one crore.',
  'crores': 'Scales the number by one crore.',
};
